name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      OPENAI_API_KEY: sk-dummy-key-for-ci-build-only
    
    strategy:
      matrix:
        node-version: [20.15.0]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build